version: "3"

tasks:
  gen-sso:
    desc: "Generate code from proto files for sso service"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  gen-profile:
    desc: "Generate code from proto files for user profile service"
    cmds:
      - protoc -I proto proto/profile/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative